package org.example.domain.repository
import org.example.domain.Sleep
import org.example.domain.db.Sleeps
import org.example.utils.mapToSleep
import org.jetbrains.exposed.sql.insert
import org.jetbrains.exposed.sql.selectAll
import org.jetbrains.exposed.sql.transactions.transaction
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule
import com.fasterxml.jackson.core.JsonProcessingException;
import org.example.domain.Nutrition
import org.example.domain.db.Nutritions
import org.example.utils.mapToNutrition
import org.jetbrains.exposed.sql.SqlExpressionBuilder.eq
import org.jetbrains.exposed.sql.deleteWhere
import org.jetbrains.exposed.sql.update
import java.time.LocalDate;

class SleepDAO {
    //Get all the sleep in the database regardless of user id
    fun getAll(): ArrayList<Sleep> {
        val sleepsList: ArrayList<Sleep> = arrayListOf()
        transaction {
            Sleeps.selectAll().map {
                sleepsList.add(mapToSleep(it))
            }
        }
        return sleepsList
    }

    fun findBySleepId(id: Int): Sleep?{
        return transaction {
            Sleeps
                .selectAll().where { Sleeps.id eq id}
                .map{ mapToSleep(it) }
                .firstOrNull()
        }
    }


    //Find all sleep for a specific user id
    fun findByUserId(userId: Int): List<Sleep> {
        return transaction {
            Sleeps.selectAll().where { Sleeps.userId eq userId }
                .map { mapToSleep(it) }
        }
    }

    fun save(sleep: Sleep): Int {
        return transaction {
            val sleepId = Sleeps.insert {
                it[sleepStart] = sleep.sleepStart
                it[sleepEnd] = sleep.sleepEnd
                it[sleepDuration] = sleep.sleepDuration
                it[bedtimeReminder] = sleep.bedtimeReminder
                it[userId] = sleep.userId
            } get Sleeps.id
            //returns the activity id as generated by the table
            sleepId
        }
    }


    fun updateBySleepId(sleepId: Int, sleepToUpdate: Sleep) : Int{
        return transaction {
            Sleeps.update ({
                Sleeps.id eq sleepId}) {
                it[sleepStart] = sleepToUpdate.sleepStart
                it[sleepEnd] = sleepToUpdate.sleepEnd
                it[sleepDuration] = sleepToUpdate.sleepDuration
                it[bedtimeReminder] = sleepToUpdate.bedtimeReminder
                it[userId] = sleepToUpdate.userId
            }
        }
    }

    fun deleteBySleepId (sleepId: Int): Int{
        return transaction{
            Sleeps.deleteWhere { Sleeps.id eq sleepId }
        }
    }

    fun deleteByUserId (userId: Int): Int{
        return transaction{
            Sleeps.deleteWhere { Sleeps.userId eq userId }
        }
    }
}