package org.example.domain.repository

import org.example.domain.Sleep
import org.example.domain.Statistic
import org.example.domain.db.Nutritions
import org.example.domain.db.Sleeps
import org.example.domain.db.Statistics
import org.example.utils.mapToSleep
import org.example.utils.mapToStatistic
import org.jetbrains.exposed.sql.SqlExpressionBuilder.eq
import org.jetbrains.exposed.sql.deleteWhere
import org.jetbrains.exposed.sql.insert
import org.jetbrains.exposed.sql.selectAll
import org.jetbrains.exposed.sql.transactions.transaction
import org.jetbrains.exposed.sql.update

class StatisticDAO {
    //Get all the statistic in the database regardless of user id
    fun getAll(): ArrayList<Statistic> {
        val statisticsList: ArrayList<Statistic> = arrayListOf()
        transaction {
            Statistics.selectAll().map {
                statisticsList.add(mapToStatistic(it))
            }
        }
        return statisticsList
    }

    fun findByStatisticId(id: Int): Statistic?{
        return transaction {
            Statistics
                .selectAll().where { Statistics.id eq id}
                .map{ mapToStatistic(it) }
                .firstOrNull()
        }
    }


    //Find all statistic for a specific user id
    fun findByUserId(userId: Int): List<Statistic> {
        return transaction {
            Statistics.selectAll().where { Statistics.userId eq userId }
                .map { mapToStatistic(it) }
        }
    }

    //Save a statistic to the database
    fun save(statistic: Statistic): Int {
        return transaction {
            val statisticId = Statistics.insert {
                it[totalSleepHours] = statistic.totalSleepHours
                it[averageCalories] = statistic.averageCalories
                it[totalActivityHours] = statistic.totalActivityHours
                it[weekStart] = statistic.weekStart
                it[weekEnd] = statistic.weekEnd
                it[userId] = statistic.userId
            } get Statistics.id
            //returns the activity id as generated by the table
            statisticId
        }
    }

    fun updateByStatisticId(statisticId: Int, statisticToUpdate: Statistic) : Int{
        return transaction {
            Statistics.update ({
                Statistics.id eq statisticId}) {
                it[totalSleepHours] = statisticToUpdate.totalSleepHours
                it[averageCalories] = statisticToUpdate.averageCalories
                it[totalActivityHours] = statisticToUpdate.totalActivityHours
                it[weekStart] = statisticToUpdate.weekStart
                it[weekEnd] = statisticToUpdate.weekEnd
                it[userId] = statisticToUpdate.userId
            }
        }
    }

    fun deleteByStatisticId (statisticId: Int): Int{
        return transaction{
            Statistics.deleteWhere { Statistics.id eq statisticId }
        }
    }

    fun deleteByUserId (userId: Int): Int{
        return transaction{
            Statistics.deleteWhere { Statistics.userId eq userId }
        }
    }
}