openapi: 3.0.1
info:
  title: Health API
  description: API for user activities, nutrition, sleep, and statistics.
  version: 1.0.0
paths:
  /api/users:
    get:
      summary: Get all users
      operationId: getAllUsers
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Add a new user
      operationId: addUser
      requestBody:
        description: User to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created
  /api/users/{user-id}:
    get:
      summary: Get user by ID
      operationId: getUserByUserId
      parameters:
        - name: user-id
          in: path
          required: true
          description: User ID
          schema:
            type: integer
      responses:
    patch:
      summary: Update user by ID
      operationId: updateUser
      parameters:
        - name: user-id
          in: path
          required: true
          description: User ID
          schema:
            type: integer
      requestBody:
        description: Updated user data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
    delete:
      summary: Delete user by ID
      operationId: deleteUser
      parameters:
        - name: user-id
          in: path
          required: true
          description: User ID
          schema:
            type: integer
      responses:
        '204':
          description: User deleted
  /api/activities:
    get:
      summary: Get all activities
      operationId: getAllActivities
      responses:
        '200':
          description: A list of activities
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Activity'
    post:
      summary: Add a new activity
      operationId: addActivity
      requestBody:
        description: Activity to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Activity'
      responses:
        '201':
          description: Activity created
  /api/activities/{activity-id}:
    get:
      summary: Get activity by ID
      operationId: getActivitiesByActivityId
      parameters:
        - name: activity-id
          in: path
          required: true
          description: Activity ID
          schema:
            type: integer
      responses:
    patch:
      summary: Update activity by ID
      operationId: updateActivity
      parameters:
        - name: activity-id
          in: path
          required: true
          description: Activity ID
          schema:
            type: integer
      requestBody:
        description: Updated activity data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Activity'
      responses:
    delete:
      summary: Delete activity by ID
      operationId: deleteActivityByActivityId
      parameters:
        - name: activity-id
          in: path
          required: true
          description: Activity ID
          schema:
            type: integer
      responses:
  /api/users/{user-id}/activities:
    get:
      summary: Get activities by user ID
      operationId: getActivitiesByUserId
      parameters:
        - name: user-id
          in: path
          required: true
          description: User ID
          schema:
            type: integer
      responses:
    delete:
      summary: Delete activities by user ID
      operationId: deleteActivitiesByUserId
      parameters:
        - name: user-id
          in: path
          required: true
          description: User ID
          schema:
            type: integer
      responses:
  /api/nutritions:
    get:
      summary: Get all nutritions
      operationId: getAllNutritions
      responses:
        '200':
          description: A list of nutritions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Nutrition'
    post:
      summary: Add a new nutrition
      operationId: addNutrition
      requestBody:
        description: Nutrition to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Nutrition'
      responses:
        '201':
          description: Nutrition created
  /api/nutritions/{nutrition-id}:
    get:
      summary: Get nutrition by ID
      operationId: getNutritionsByNutritionId
      parameters:
        - name: nutrition-id
          in: path
          required: true
          description: Nutrition ID
          schema:
            type: integer
      responses:
    patch:
      summary: Update nutrition by ID
      operationId: updateNutrition
      parameters:
        - name: nutrition-id
          in: path
          required: true
          description: Nutrition ID
          schema:
            type: integer
      requestBody:
        description: Updated nutrition data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Nutrition'
      responses:
    delete:
      summary: Delete nutrition by ID
      operationId: deleteNutritionByNutritionId
      parameters:
        - name: nutrition-id
          in: path
          required: true
          description: Nutrition ID
          schema:
            type: integer
      responses:
  /api/users/{user-id}/nutritions:
    get:
      summary: Get nutritions by user ID
      operationId: getNutritionsByUserId
      parameters:
        - name: user-id
          in: path
          required: true
          description: User ID
          schema:
            type: integer
      responses:
    delete:
      summary: Delete nutritions by user ID
      operationId: deleteNutritionsByUserId
      parameters:
        - name: user-id
          in: path
          required: true
          description: User ID
          schema:
            type: integer
      responses:
  /api/sleeps:
    get:
      summary: Get all sleeps
      operationId: getAllSleeps
      responses:
        '200':
          description: A list of sleeps
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sleep'
    post:
      summary: Add a new sleep
      operationId: addSleep
      requestBody:
        description: Sleep data to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sleep'
      responses:
        '201':
          description: Sleep created
  /api/sleeps/{sleep-id}:
    get:
      summary: Get sleep by ID
      operationId: getSleepsBySleepId
      parameters:
        - name: sleep-id
          in: path
          required: true
          description: Sleep ID
          schema:
            type: integer
      responses:
    patch:
      summary: Update sleep by ID
      operationId: updateSleep
      parameters:
        - name: sleep-id
          in: path
          required: true
          description: Sleep ID
          schema:
            type: integer
      requestBody:
        description: Updated sleep data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sleep'
      responses:
    delete:
      summary: Delete sleep by ID
      operationId: deleteSleepBySleepId
      parameters:
        - name: sleep-id
          in: path
          required: true
          description: Sleep ID
          schema:
            type: integer
      responses:
  /api/users/{user-id}/sleeps:
    get:
      summary: Get sleeps by user ID
      operationId: getSleepsByUserId
      parameters:
        - name: user-id
          in: path
          required: true
          description: User ID
          schema:
            type: integer
      responses:
    delete:
      summary: Delete sleeps by user ID
      operationId: deleteSleepsByUserId
      parameters:
        - name: user-id
          in: path
          required: true
          description: User ID
          schema:
            type: integer
      responses:
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
    Activity:
      type: object
      properties:
        id:
          type: integer
        description:
          type: string
        duration:
          type: number
          format: double
        calories:
          type: integer
        started:
          type: string
          format: date-time
        userId:
          type: integer
    Nutrition:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        calories:
          type: integer
        fat:
          type: number
          format: double
        carbs:
          type: number
          format: double
        protein:
          type: number
          format: double
        waterIntake:
          type: number
          format: double
        loggedDate:
          type: string
          format: date-time
        userId:
          type: integer
    Sleep:
      type: object
      properties:
        id:
          type: integer
        sleepStart:
          type: string
          format: date-time
        sleepEnd:
          type: string
          format: date-time
        sleepDuration:
          type: number
          format: double
        bedtimeReminder:
          type: boolean
        userId:
          type: integer
    Statistic:
      type: object
      properties:
        id:
          type: integer
        totalSleepHours:
          type: number
          format: double
        averageCalories:
          type: integer
        totalActivityHours:
          type: number
          format: double
        weekStart:
          type: string
        weekEnd:
          type: string
        userId:
          type: integer